from pybricks.pupdevices import Motor
from pybricks.parameters import Port, Direction, Stop
from pybricks.robotics import DriveBase
from pybricks.tools import wait, multitask, run_task
from pybricks.hubs import PrimeHub

# --- Inicializa motores ---
hub = PrimeHub()
left_motor = Motor(Port.A, Direction.COUNTERCLOCKWISE)
right_motor = Motor(Port.B)
motorc = Motor(Port.C)
motord = Motor(Port.D, Direction.CLOCKWISE, [12, 36, 12, 20])
# --- Inicializa DriveBase ---
drive_base = DriveBase(left_motor, right_motor, wheel_diameter=62.4, axle_track=120)
drive_base.use_gyro(True)
drive_base.straight(-10)
drive_base.reset()
# --- Missão inicial da base ---
drive_base.settings(straight_speed=800,)
motord.run_time(-600, 1100)
motord.reset_angle(0)
drive_base.straight(300)
drive_base.turn(6)
drive_base.straight(600)
drive_base.turn(-6)
drive_base.straight(120)
wait(200)
drive_base.settings(straight_speed=200, turn_rate=90)
drive_base.straight(-136)
wait(200)
drive_base.turn(90)
wait(200)
hub.imu.reset_heading(90)
motord.run_time(600, 1200)
motord.reset_angle(0)
motorc.run_angle(1000, 1600)
drive_base.settings(straight_speed=100, turn_rate=120)
drive_base.straight(120)
wait(20)
motord.run_angle(500, -122)
motorc.run_angle(1000, -870)
wait(1000)
motorc.run_angle(1000, 1120)
drive_base.straight(-100)
motord.run_angle(1000, -250)
drive_base.reset()
drive_base.turn(47)
drive_base.settings(straight_speed=800)
drive_base.straight(360)
motorc.run_angle(1000, -500)
drive_base.turn(-16.5)
motorc.run_angle(1000, -500)
drive_base.turn(16.5)
wait(100)
drive_base.straight(-130)
drive_base.settings(straight_speed=1000, turn_rate=120)
drive_base.turn(-25)
drive_base.straight(-200)
drive_base.turn(-85)
async def andarwhilelevantamotor():
    await multitask(drive_base.straight(-1000), motorc.run_angle(1000, -800))
run_task(andarwhilelevantamotor())